Add 'connects-to' label
gorkem/app-labels pull request #10
Opened 2019-04-12 16:44 UTC by sbose78

This generic label is used to denote that a component A might be talking to Component B to another using - 
A service/route exposed by Component B which is configured *into* the environment variable of Component A.

2019-04-17 09:26 UTC, DhritiShikhar commented
@sbose78 why is this `connects-to` an annotation and not a label?

2019-04-22 13:13 UTC, sbose78 commented
> What is the string value that connects-to uses? Is it the app.kubernetes.io/name value or app.kubernetes.io/instance value?

`instance` preferably.

> Can any component have more than one connects-to annotation?

Yes.

> why is this connects-to an annotation and not a label?

Because `connects-to` value is not to be used to actually create a connection.

2019-04-22 17:34 UTC, sspeiche commented
LGTM

2019-04-24 22:55 UTC, gorkem requested changes

2019-04-24 22:55 UTC, gorkem commented on labels-annotation-for-openshift.adoc
> +
I am not sure if we are clear about what value is expected on this definition. Is it `app.kubernetes.io/instance` or `app.kubernetes.io/name` or a combination of both?

2019-04-24 22:55 UTC, gorkem commented on labels-annotation-for-openshift.adoc
> +| e.g. Component `front-end` has a `connects-to` which has a value `backend`
I am not sure about this example. Can we try to put some real values?

2019-04-24 22:55 UTC, gorkem approved these changes

2019-04-24 22:55 UTC, merged